name: http-types

# Trigger the workflow on pull requests or a push (but only for the 'master' branch)
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "**.hs"
      - "**.cabal"
      - "stack.yaml"
      - ".github/workflows/ci.yml"
  push:
    branches: [master]

jobs:
  cabal:
    name: cabal / ghc-${{matrix.ghc}} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      MANUAL_RESET: "v5"
    continue-on-error: ${{ matrix.ghc == '9.14.1' || matrix.os == 'macos-latest' }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest # Is giving issues for some reason
        cabal: ["3.16.1.0"] # we set a concrete cabal so we can cache correctly
        ghc:
          - "9.6.7"
          - "9.8.4"
          - "9.10.3"
          - "9.12.4"
          - "9.14.1"

    steps:
      - name: "Set ENV / PATH"
        id: env-vars
        run: |
          if [[ "${{ matrix.os }}" == 'macos-latest' ]]; then
            echo "${HOME}/.ghcup/bin" >> $GITHUB_PATH
          fi

          echo "GHCUP_PATH=${HOME}/.ghcup" >> $GITHUB_ENV

      - name: Clone Project
        uses: actions/checkout@v6

      - name: Cache GHCup
        uses: actions/cache@v6
        id: ghcup-cache
        with:
          path: |
            ${{ env.GHCUP_PATH }}/bin/*
            ${{ env.GHCUP_PATH }}/cabal/${{ matrix.cabal }}/*
            ${{ env.GHCUP_PATH }}/config.yaml
            ${{ env.GHCUP_PATH }}/ghc/${{ matrix.ghc }}/bin
            ${{ env.GHCUP_PATH }}/ghc/${{ matrix.ghc }}/lib
          key: CI-ghcup-cabal-${{ env.MANUAL_RESET }}-${{ matrix.os }}-${{ matrix.ghc }}

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        if: steps.ghcup-cache.outputs.cache-hit != 'true'
        id: ghcup-install
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - uses: actions/cache@v6
        name: Cache cabal-store
        id: deps-cache
        with:
          path: ~/.cabal
          key: CI-deps-cache-${{ env.MANUAL_RESET }}-${{ matrix.os }}-${{ matrix.ghc }}

      - name: Build Dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        id: build-deps
        run: |
          cabal update
          cabal build all --only-dependencies \
            --enable-tests --enable-benchmarks \
            --write-ghc-environment-files=always \
            --ghc-option='-Wall'

      - name: Build
        run: |
          cabal build all \
            --enable-tests --enable-benchmarks \
            --write-ghc-environment-files=always \
            --ghc-option='-Wall'
      - name: Test
        run: |
          cabal test test:spec --enable-tests --ghc-option='-Wall'
      - name: Test Docs
        run: |
          cabal exec -- cabal test test:doctests --enable-tests --ghc-option='-Wall'
    # # We probably want to add benchmarks at some point, just to make sure
    # # functions don't regress in performance too much?
    # - name: Bench
    #   run: |
    #     cabal bench --enable-benchmarks

  stack:
    name: stack ${{ matrix.resolver }}
    runs-on: ubuntu-latest
    env:
      MANUAL_RESET: v3
    # This makes the CI jobs not all be cancelled if nightly fails to build.
    # However, if nightly fails to build, CI still gets a red X in the GitHub UI.
    # Ideally we want CI as a whole to pass even if nightly fails.
    # There doesn't appear to be a way to work around this for now.
    #
    # When some sort of `allow-failure` functionality is available in GitHub
    # actions, we should switch to it:
    # https://github.com/actions/toolkit/issues/399
    continue-on-error: ${{ matrix.resolver == 'nightly' || matrix.resolver == 'lts-12' }}
    strategy:
      matrix:
        include:
          - resolver: "lts-12"
            ghc: "8.4.4"
          - resolver: "lts-22"
            ghc: "9.6.7"
          - resolver: "lts-23"
            ghc: "9.8.4"
          - resolver: "lts-24"
            ghc: "9.10.3"
          - resolver: "nightly"
            ghc: "9.12.4"

    steps:
      - name: "Set ENV vars per LTS"
        id: env-vars
        run: |
          STACK_ROOT="$HOME/.stack"
          GHCUP_PATH="~/.ghcup"
          GHCUP_GHC_PATH="${GHCUP_PATH}/ghc/${{ matrix.ghc }}"

          # And then we expose these variables in the 'env'
          echo "GHC_VERSION=$GHC_VERSION" >> $GITHUB_ENV
          echo "GHCUP_PATH=$GHCUP_PATH" >> $GITHUB_ENV
          echo "GHCUP_GHC_PATH=$GHCUP_GHC_PATH" >> $GITHUB_ENV
          echo "STACK_ROOT=$STACK_ROOT" >> $GITHUB_ENV

      - name: Clone project
        uses: actions/checkout@v6

      - name: Cache GHCup
        uses: actions/cache@v6
        id: ghcup-cache
        with:
          path: |
            ${{ env.GHCUP_PATH }}/bin/*
            ${{ env.GHCUP_PATH }}/config.yaml
            ${{ env.GHCUP_GHC_PATH }}/bin
            ${{ env.GHCUP_GHC_PATH }}/lib
            ${{ env.GHCUP_PATH }}/stack/*
          key: CI-ghcup-stack-${{ env.MANUAL_RESET }}-${{ matrix.ghc }}

      - name: Setup Haskell Stack
        uses: haskell-actions/setup@v2
        if: steps.ghcup-cache.outputs.cache-hit != 'true'
        with:
          stack-version: "latest"
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-setup-ghc: false

      - name: Cache Pantry (Stackage package index)
        id: pantry-cache
        uses: actions/cache@v6
        with:
          path: |
            ${{ env.STACK_ROOT }}/pantry
            !${{ env.STACK_ROOT }}/pantry/hackage/00-index.tar
            !${{ env.STACK_ROOT }}/pantry/hackage/00-index.tar.gz
          key: CI-pantry-${{ env.MANUAL_RESET }}

      - name: Recompute Stackage package index
        if: steps.pantry-cache.outputs.cache-hit != 'true'
        id: pantry-install
        run: |
          # Populates $STACK_ROOT/pantry
          #
          # The extra arguments are probably superfluous, but stack's caching
          # is weird sometimes, so we keep everything equal when possible.
          stack update \
            --system-ghc --no-terminal \
            --resolver="${{ matrix.resolver }}"

      - name: Cache Dependencies
        id: deps-cache
        uses: actions/cache@v6
        with:
          path: |
            ${{ env.STACK_ROOT }}/stack.sqlite3
            ${{ env.STACK_ROOT }}/snapshots
            #     [EXCLUDES]
            # Don't cache any haddocks or other docs
            !${{ env.STACK_ROOT }}/snapshots/**/doc
          key: CI-deps-cache-${{ env.MANUAL_RESET }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml', 'http-types.cabal') }}
          restore-keys: |
            CI-deps-cache-${{ env.MANUAL_RESET }}-${{ matrix.resolver }}-

      - name: Build dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        id: deps-install
        run: |
          stack build --test \
            --system-ghc --no-terminal \
            --resolver="${{ matrix.resolver }}" \
            --only-dependencies --no-run-tests \
            --ghc-options='-j -Wall'

      # This gets it's own build, since the test suite doesn't build on LTS-12
      - name: Build lts-12
        if: "${{ matrix.resolver == 'lts-12' }}"
        run: |
          stack build \
            --system-ghc --no-terminal \
            --resolver="${{ matrix.resolver }}" \
            --ghc-options='-j -Wall'

      - name: Build
        if: "${{ matrix.resolver != 'lts-12' }}"
        run: |
          stack build \
            --system-ghc --no-terminal \
            --resolver=${{ matrix.resolver }} \
            --test --bench \
            --no-run-tests --no-run-benchmarks \
            --ghc-options='-Wall'
      - name: Test
        if: "${{ matrix.resolver != 'lts-12' }}"
        run: |
          stack test http-types:test:spec \
            --system-ghc --no-terminal \
            --no-rerun-tests \
            --resolver=${{ matrix.resolver }}
      - name: Test Docs
        if: "${{ matrix.resolver != 'lts-12' }}"
        run: |
          stack test http-types:test:doctests \
            --system-ghc --no-terminal \
            --resolver=${{ matrix.resolver }}

    # # We probably want to add benchmarks at some point, just to make sure
    # # functions don't regress in performance too much?
    # - name: Bench
    #   run: |
    #     stack bench ${{ matrix.resolver }}
